### ISSUE TITLE
Feature: Support using a TOML "dotfile" config file in the user's homedir

### ISSUE THREAD

**Issue by hpatel292-seneca** [uday-rana/codeshift#35]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem.

**Comment by uday-rana** [comment]
Hi Mayank, [Lab 04](https://github.com/humphd/topics-in-open-source-2024/wiki/lab-4) states:

> Pick a new repo from the [0.1 Submissions list](https://github.com/humphd/topics-in-open-source-2024/wiki/release-0.1#submission), ideally one that you have NOT worked on before.

Since we worked together for Lab 2, please find another repository for this week's lab. Thanks!
